apiVersion: apps/v1
kind: Deployment
metadata:
  # 换成对应的服务名
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  # 选定需要管理的 Pod 标签
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: "registry.cn-shenzhen.aliyuncs.com/gsmini/frontend:v3"
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime

---
apiVersion: v1
kind: Service
metadata:
  # 服务命名规则：统一在末尾加"-svc"
  name: frontend-svc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app:  frontend
  type: ClusterIP
